<!-- ══ PRODUCER INFO ══ -->
<div id="p-producer" class="panel">

  <div class="kpi-g">
    <div class="kc"><div class="ki" style="--ib:#E3F2FD">👤</div><div class="kn">10,482</div><div class="kl">Registered producers</div></div>
    <div class="kc"><div class="ki" style="--ib:#FFF3D6">📅</div><div class="kn">41 yrs</div><div class="kl">Average age</div><div class="kt ty">Range 18–80</div></div>
    <div class="kc"><div class="ki" style="--ib:#E9F7EC">💍</div><div class="kn">82%</div><div class="kl">Married</div></div>
    <div class="kc"><div class="ki" style="--ib:#FFF3D6">🎓</div><div class="kn">31%</div><div class="kl">Graduate+</div></div>
    <div class="kc"><div class="ki" style="--ib:#E3F2FD">📞</div><div class="kn">98%</div><div class="kl">Have mobile</div></div>
    <div class="kc"><div class="ki" style="--ib:#F3E5F5">📋</div><div class="kn">74%</div><div class="kl">NBB registered</div></div>
  </div>
  <div class="g3">
    <div class="cc"><div class="ct">Gender (sec 1.8)</div><div class="dw" style="margin-top:10px"><svg width="72" height="72" viewBox="0 0 36 36" role="img" aria-label="76% male 24% female"><circle cx="18" cy="18" r="13" fill="none" stroke="#F7F0E4" stroke-width="5"/><circle cx="18" cy="18" r="13" fill="none" stroke="#1976D2" stroke-width="5" stroke-dasharray="76 24" stroke-dashoffset="25" stroke-linecap="round"/><circle cx="18" cy="18" r="13" fill="none" stroke="#F06292" stroke-width="5" stroke-dasharray="24 76" stroke-dashoffset="-51" stroke-linecap="round"/></svg><div class="leg"><div class="lr"><div class="ld" style="background:#1976D2"></div>Male (76%)</div><div class="lr"><div class="ld" style="background:#F06292"></div>Female (24%)</div></div></div></div>
    <div class="cc"><div class="ct">Religion (sec 1.9)</div><div class="bars" style="margin-top:10px"><div class="br"><div class="bl w90">Hindu</div><div class="bt"><div class="bf fa" style="width:72%">72%</div></div></div><div class="br"><div class="bl w90">Muslim</div><div class="bt"><div class="bf fb" style="width:18%">18%</div></div></div><div class="br"><div class="bl w90">Sikh</div><div class="bt"><div class="bf ft" style="width:6%">6%</div></div></div><div class="br"><div class="bl w90">Christian</div><div class="bt"><div class="bf fp" style="width:4%">4%</div></div></div></div></div>
    <div class="cc"><div class="ct">Caste (sec 1.10)</div><div class="bars" style="margin-top:10px"><div class="br"><div class="bl w90">General</div><div class="bt"><div class="bf fa" style="width:34%">34%</div></div></div><div class="br"><div class="bl w90">OBC</div><div class="bt"><div class="bf fg" style="width:42%">42%</div></div></div><div class="br"><div class="bl w90">SC</div><div class="bt"><div class="bf fb" style="width:18%">18%</div></div></div><div class="br"><div class="bl w90">ST</div><div class="bt"><div class="bf fp" style="width:6%">6%</div></div></div></div></div>
    <div class="cc"><div class="ct">Education (sec 1.11)</div><div class="bars" style="margin-top:10px"><div class="br"><div class="bl w90">Graduate+</div><div class="bt"><div class="bf fg" style="width:31%">31%</div></div></div><div class="br"><div class="bl w90">High school</div><div class="bt"><div class="bf fa" style="width:19%">19%</div></div></div><div class="br"><div class="bl w90">Secondary</div><div class="bt"><div class="bf fa" style="width:21%">21%</div></div></div><div class="br"><div class="bl w90">Primary</div><div class="bt"><div class="bf fc" style="width:18%">18%</div></div></div><div class="br"><div class="bl w90">Uneducated</div><div class="bt"><div class="bf fr" style="width:11%">11%</div></div></div></div></div>
    <div class="cc"><div class="ct">Marital status (sec 1.12)</div><div class="bars" style="margin-top:10px"><div class="br"><div class="bl w90">Married</div><div class="bt"><div class="bf fg" style="width:82%">82%</div></div></div><div class="br"><div class="bl w90">Unmarried</div><div class="bt"><div class="bf fa" style="width:13%">13%</div></div></div><div class="br"><div class="bl w90">Widow/er</div><div class="bt"><div class="bf fp" style="width:5%">5%</div></div></div></div></div>
    <div class="cc"><div class="ct">Main occupation (sec 1.14)</div><div class="bars" style="margin-top:10px"><div class="br"><div class="bl w90">Agriculture</div><div class="bt"><div class="bf fg" style="width:58%">58%</div></div></div><div class="br"><div class="bl w90">Animal husb.</div><div class="bt"><div class="bf fa" style="width:19%">19%</div></div></div><div class="br"><div class="bl w90">Private job</div><div class="bt"><div class="bf fb" style="width:11%">11%</div></div></div><div class="br"><div class="bl w90">Trade</div><div class="bt"><div class="bf fp" style="width:8%">8%</div></div></div><div class="br"><div class="bl w90">Other</div><div class="bt"><div class="bf ft" style="width:4%">4%</div></div></div></div></div>
  </div>
</div>
